### PR TITLE
PDF Layout modified

### PR DESCRIPTION
**Pull request by Tanvish**
The layout for the pdf needed to be fixed for cases when there are more than few passengers injured.

### CODE REVIEW

**Comment by Anbranin** [comment]
Could you provide a screenshot ?

**Comment by Anbranin** [comment]
For the love of all that is good in the world
Please fix those broken tests on master

**Comment by Anbranin** [comment]
I didn't mean to press close and comment. OMG

**Comment by Tanvish** [comment]
# Screenshots

## For more than 2 passengers or a long description, we will print the accident description on the next page.
Screen Shot 2019-11-01 at 1 13 50 PM

## Otherwise we can fit the passenger and description on the first page itself.
Screen Shot 2019-11-01 at 1 14 49 PM

**Comment by Tanvish** [comment]
Should I merge this PR?

**Comment by Anbranin** [comment]
Since you can't deploy it, I'd hold off... @dfaulken what's the next step?

**Comment by dfaulken** [comment]
Sorry for slow reply - notification got buried

It seems like we're good to merge and deploy.

**Pull request merged**
