### PR TITLE
Fix occasional failures with DatabaseCleaner

### PR DESCRIPTION
**Pull request by jforgue**
This should fix those failing system tests. Depends on #249.

### CODE REVIEW

**Comment by werebus** [comment]
So, two quick drive-by comments:

1. It seems like you specified that _all_ system test require JS. That seems unlikely, but I will concede that we were using headless Chrome for all system test already.  However, given that, what does this PR accomplish on that end.
2.  Can you explain _why_ we need to resort to Database Cleaner?

**Comment by jforgue** [comment]
1. I did assume all system tests needed selenium, but like you said that's unlikely. I can go back through and change that.

2. I was getting occasional failures on some system tests when a form field was filled in but it was expected to be blank. One specific test would be `/spec/system/supervisors/special_supervisor_report_fields_spec.rb:155` where we would expect to get an error message after submitting with a blank field. However, the field was filled (presumably from a previous test) and the form was submitted successfully.

**Comment by jforgue** [comment]
Here is the test in question:
```
describe 'special supervisor report fields', js: true do
  let(:supervisor) { create :user, :supervisor }
  before(:each) { when_current_user_is supervisor }
  let(:supervisor_incident_report) { create :incident_report, user: supervisor }
  let(:incident) do
    create :incident, supervisor_incident_report: supervisor_incident_report
  end

  describe 'FTA threshold related fields', js: true do
    context 'with FTA threshold met' do
      before :each do
        incident.supervisor_report.update! completed_drug_or_alcohol_test: false,
                                           fta_threshold_not_met: false,
                                           driver_discounted: true,
                                           reason_driver_discounted: 'Placeholder'
        visit edit_supervisor_report_url(incident.supervisor_report)
      end

      it 'requires explaining how the FTA threshold was not met' do
        check 'Accident does not meet FTA post-accident testing criteria. Therefore, no drug or alcohol testing is permitted under FTA.'
        click_button 'Save supervisor report'
        wait_for_ajax!
        expect(page)
          .to have_text 'This supervisor report has 1 missing value and so cannot be marked as completed.'
      end
    end
end
```

**Comment by jforgue** [comment]
Closing for now. There are two tests in question and they only seem to fail on a first build.

**Pull request closed without merging**
